document.write('<script src="profile.js"></script>');
(function(){
  const fields=[...document.querySelectorAll('[data-print]')];
  const inputs=[...document.querySelectorAll('input,textarea,select')];
  const optionalEventIds=['eventDate','eventTime','transportEventDate','transportEventTime'];
  optionalEventIds.forEach(id=>document.getElementById(id)?.removeAttribute('required'));
  const value=id=>{const el=document.getElementById(id);return el?el.value.trim():''};
  const isSeptember2026=value=>{const match=/^2026-09-(\d{2})$/.exec(value);return Boolean(match&&Number(match[1])>=1&&Number(match[1])<=30)};
  const formatDate=value=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(value))return '';const [year,month,day]=value.split('-');return `${day}.${month}.${year}`};
  const formatTime=value=>{if(!value)return '';const [hours,minutes]=value.split(':');return `${hours} часов ${minutes} минут`};
  const optionalFragments=new WeakMap();
  function normalizeDateText(){const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);nodes.forEach(node=>{node.textContent=node.textContent.replace(/» сентября 2026 года/g,'»').replace(/» сентября 2026 г\./g,'»')})}
  function wrapEventTimePrefix(){document.querySelectorAll('[data-print="eventTime"]').forEach(el=>{if(el.parentElement?.hasAttribute('data-event-time-prefix'))return;const before=el.previousSibling;if(!before||before.nodeType!==Node.TEXT_NODE)return;const match=/(На момент |в |В )$/.exec(before.textContent);if(!match)return;const prefix=document.createElement('span');prefix.dataset.eventTimePrefix='';prefix.append(before.splitText(before.length-match[0].length));before.parentNode.insertBefore(prefix,el);prefix.appendChild(el)})}
  function sync(){normalizeDateText();wrapEventTimePrefix();const transportDate=value('transportEventDate');const transportTime=value('transportEventTime');const transportUik=value('transportUik');const escape=value=>value.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));const transportParagraph=document.getElementById('transportEventDate')?document.querySelector('#doc p'):null;if(transportParagraph)transportParagraph.innerHTML=transportDate?`${transportTime?`Ориентировочно в <span class="val">${escape(transportTime)}</span>`:'Ориентировочно'} <span class="val">${escape(formatDate(transportDate))}</span> мной выявлены признаки нарушения избирательного законодательства, выразившиеся в осуществлении неустановленными лицами организованного подвоза более 100 избирателей для голосования в помещении УИК <span class="val">${escape(transportUik)}</span>.`:'';const eventTimePrefix=document.querySelector('[data-event-time-prefix]');if(eventTimePrefix)eventTimePrefix.hidden=!value('eventTime');fields.forEach(el=>{const raw=value(el.dataset.print);const printed=el.hasAttribute('data-print-date')?formatDate(raw):el.hasAttribute('data-print-time')?formatTime(raw):raw;if(el.dataset.print==='serial'){const paragraph=el.closest('p');if(paragraph)paragraph.hidden=!printed}if(el.dataset.print==='actDate'){let fragment=optionalFragments.get(el);if(!fragment){fragment={before:el.previousSibling,beforeText:el.previousSibling.textContent,after:el.nextSibling,afterText:el.nextSibling.textContent};optionalFragments.set(el,fragment)}fragment.before.textContent=printed?fragment.beforeText:fragment.beforeText.replace(/\s*«\s*$/,'');fragment.after.textContent=printed?fragment.afterText:fragment.afterText.replace(/^»\s*сентября 2026\s*/,'');el.hidden=!printed}el.textContent=printed})}
  function validate(){const currentInputs=[...inputs,...document.querySelectorAll('#transportUik,#transportEventDate,#transportEventTime')];const requiredIds=document.body.dataset.printRequired?.split(',').map(id=>id.trim()).filter(Boolean);const field=currentInputs.find(el=>(requiredIds?requiredIds.includes(el.id):(el.required||el.dataset.required==='true'))&&!value(el.id));if(field){const label=document.querySelector(`label[for="${field.id}"]`);window.alert(`Заполните обязательное поле: ${label?label.textContent.trim():field.id}`);field.focus();return false}const invalidDate=currentInputs.find(el=>el.type==='date'&&value(el.id)&&(!isSeptember2026(value(el.id))||value(el.id)<el.min||value(el.id)>el.max));if(invalidDate){const label=document.querySelector(`label[for="${invalidDate.id}"]`);window.alert(`Укажите дату в сентябре 2026 года: ${label?label.textContent.trim():invalidDate.id}`);invalidDate.focus();return false}return true}
  window.fillExample=function(){const data=JSON.parse(document.body.dataset.example||'{}');Object.keys(data).forEach(id=>{const el=document.getElementById(id);if(el)el.value=data[id]});sync()};
  window.clearForm=function(){[...inputs,...document.querySelectorAll('#transportUik,#transportEventDate,#transportEventTime')].forEach(el=>{el.value=''});sync()};
  window.generatePDF=function(){if(!validate())return;sync();window.print()};
  inputs.forEach(el=>el.addEventListener('input',sync));
  inputs.forEach(el=>el.addEventListener('change',sync));
  if(window.VoteProfile)window.VoteProfile.apply();
  setTimeout(()=>{if(window.VoteProfile)window.VoteProfile.apply()},0);
  sync();
})();
